# Prepare CloudFormation Templates
- name: Preparing CloudFormation Templates
  hosts: "{{ env }}"
  roles:
    - prepare-cf-templates
  gather_facts: false 
  become: true
  tags: prepare

# Validate CloudFormation Templates
- name: Validating CloudFormation Templates
  hosts: "{{ env }}"
  roles:
    - validate-cf-templates 
  gather_facts: false
    become: true
  tags: validate

# Deploy CloudFormation Templates
- name: Deploying CloudFormation Templates  
  hosts: "{{ env }}"
  roles:
    - deploy-cf-templates
  gather_facts: false
  become: true
  tags: deploy

# # Install Mediawiki
# - name: Install mediawiki
#   roles:
#     - install-mediawiki
#   gather_facts: false
#   become: true
#   tags: install-mediawiki

#   # Validate Mediawiki
# - name: Validate Mediawiki
#   roles:
#     - validate-mediawiki
#   gather_facts: false
#   become: true
#   tags: validate-mediawiki